### PR TITLE
feat(health): Expose `HealthService` publically

### LINKED ISSUE #929: Support retrieve name of NamedService by instance
### Crates

`tonic`

### Motivation

When I'm trying to [retrieve name of health service](https://github.com/engula/engula/blob/2ba773d2a32781f0b04a863873636a04cd9722de/src/engula/src/server.rs#L87-L89), it's impossible since the exact type consist an inner struct. Although I can still copy the name string literally and fallback to `set_service_status` interface, it would be reasonable to retrieve the name of `NamedService` by instance.

### Proposal

I'll submit a patch and it should simply add a getter.

### Alternatives

N/A

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

This closes #929.

I'm glad to add some tests, but the existing `NAME` doesn't have tests and I don't have idea where to add some.

### CODE REVIEW

**Comment by tisonkun** [comment]
cc @LucioFranco

**Comment by LucioFranco** [comment]
@tisonkun looks like there is a CI failure?

**Comment by tisonkun** [comment]
@LucioFranco 2c0da18 is the fix..

**Comment by tisonkun** [comment]
@LucioFranco I think this PR is ready to merge now.

**Pull request merged**
