### PR TITLE
Update to hyper 1.0 and axum 0.7

### PR DESCRIPTION
**Pull request by ikrivosheev**
Hello! This is continue for: https://github.com/hyperium/tonic/pull/1583

Also I merged:

- https://github.com/allan2/tonic/pull/1
- https://github.com/allan2/tonic/pull/2

TODO:

- [x] update imports to use -util crates
- [x] update AddrStream and AddrIncoming
- [ ] use axum Request and Response in transport (in-progress)
- [ ] add poll_frame to impl http_body::Body (in-progress)
- [ ] remove poll_trailers from impl http_body::Body (in-progress)
- [x] fix hyper-timeout connector
- [ ] fix connect, Connect (no more hyper::client::service::Connect)
- [ ] update version, docs
- [ ] update examples
- [ ] many more (tonic-web, etc. Some of these will be in separate PRs)

Depends on:

- [x] https://github.com/hyperium/hyper/issues/3461

Closed: https://github.com/hyperium/tonic/issues/1579

### CODE REVIEW

**Comment by ikrivosheev** [comment]
Well, now I understand. I need to re-implement two structs:

1. https://docs.rs/hyper/0.14.27/hyper/client/service/struct.Connect.html
2. https://docs.rs/hyper/0.14.27/hyper/client/conn/struct.SendRequest.html
 
And `Channel` will start to compile. Great, small, but progress))

**Comment by jakubadamw** [comment]
@ikrivosheev do you plan on continuing with this PR?

**Comment by ikrivosheev** [comment]
> @ikrivosheev do you plan on continuing with this PR?

@jakubadamw , hello! Yes, I do. At the moment I need to finish tasks in hyper-util.

**Comment by rakshith-ravi** [comment]
@ikrivosheev is there anyway I can help in pushing this forward?

**Comment by rakshith-ravi** [comment]
> Hello! For the PR needs something like: https://docs.rs/hyper/0.14.28/hyper/client/service/struct.Connect.html. A service which return a service https://docs.rs/hyper/0.14.28/hyper/client/conn/struct.SendRequest.html for make http request.

[hyper-util](https://docs.rs/hyper-util) can help us here. Can we consider using some of those structs?

**Comment by ikrivosheev** [comment]
> > Hello! For the PR needs something like: https://docs.rs/hyper/0.14.28/hyper/client/service/struct.Connect.html. A service which return a service https://docs.rs/hyper/0.14.28/hyper/client/conn/struct.SendRequest.html for make http request.
> 
> [hyper-util](https://docs.rs/hyper-util) can help us here. Can we consider using some of those structs?

Yes, I saw it. But there aren't structures like in the old hyper version.

**Comment by alexrudy** [comment]
I think I got the `SendRequest` and `Connection` pieces working in #1670, but I'm running into what I think is a compiler error.

In that PR I still want to finish handling `poll_frame` and properly add graceful shutdowns (both things I punted on while just trying to get `tonic` to compile)

**Comment by LockedThread** [comment]
I really appreciate you guys working om this. I am looking forward to multiplexing Axum and Tonic in my current project. Right now I have strict dependencies on Hyper 1.0+ and Axum 0.7+.

If there is anything I can do to help out please let me know.

**Comment by alexrudy** [comment]
This branch compiles!

Tests don't pass yet, lots to do as above, but compiling is a start!

**Pull request closed without merging**
