### PR TITLE
chore: Prepare `0.4.1` release

### PR DESCRIPTION
**Pull request by Protryon**

### CODE REVIEW

**Comment by davidpdrsn** [comment]
I've submitted a couple of small PRs that would be nice to get in as well:

- https://github.com/hyperium/tonic/pull/559
- https://github.com/hyperium/tonic/pull/560
- https://github.com/hyperium/tonic/pull/561

**Comment by UebelAndre** [comment]
I'd also love if https://github.com/hyperium/tonic/pull/566 could make it in for this release 🙏

**Comment by dingelish** [comment]
hi @LucioFranco , could i have an eta for 0.4.1? Thanks!

**Comment by LucioFranco** [comment]
oh wow I must have missed this! I have been super busy at work and had some high priority things pop up. I am going to break out time today/this week to review this.

**Comment by davidpdrsn** [comment]
Working on getting this out. I did my own PR as I couldn't figure out how to update the change log here https://github.com/hyperium/tonic/pull/580. Sorry for stealing the credit @Protryon 😜

**Comment by davidpdrsn** [comment]
0.4.1 of tonic and tonic-build is on crates.io 🚀

**Pull request closed without merging**
