### PR TITLE
chore: Update to cargo-check-external-types 0.1.13

### PR DESCRIPTION
**Pull request by tottoto**
This seems to be introduced at the recent changes in `pin-project`.

https://github.com/taiki-e/pin-project/pull/357

### CODE REVIEW

**Review by jenr24-architect — APPROVED** [review]

**Comment by jenr24-architect** [comment]
Bumping for #2008

**Comment by taiki-e** [comment]
fwiw, this is a cargo-check-external-types bug: https://github.com/taiki-e/pin-project-lite/issues/86

**Comment by tottoto** [comment]
Thanks. Added a comment that these are workaround.

**Comment by taiki-e** [comment]
This issue has been fixed in cargo-check-external-types 0.1.13.

**Comment by tottoto** [comment]
Changed to update to cargo-check-external-types 0.1.13.

https://github.com/awslabs/cargo-check-external-types/releases/tag/v0.1.13

**Comment by jenr24-architect** [comment]
@LucioFranco bumping this again for #2008!

**Pull request merged**
