### PR TITLE
chore: Update from tower 0.4 to 0.5

### PR DESCRIPTION
**Pull request by kanpov**
## Motivation

#2003

## Solution

Bumped dependencies

### CODE REVIEW

**Comment by kanpov** [comment]
I never want to do this ever again, but here we are. Ready for review, everything has been upgraded to tower 0.5 and towe-http 0.6, including tests and examples so that they compile just fine.

**TL;DR for reviewers**: all changes except for the following were just bumps, the main pain was the Channel since the entire Buffer type is vastly different in its generics in 0.5, so the Svc type I removed completely and rewrote the Channel internals like so using rustc hints:
image

I'd appreciate this getting into a release so that every tonic project doesn't need to duplicate tower.

**Comment by djc** [comment]
This was done already in #1892. Unfortunately it is a change in the public API so we'd need everyone to migrate. Not sure if this change is worth doing an incompatible bump on its own.

**Comment by kanpov** [comment]
> This was done already in #1892. Unfortunately it is a change in the public API so we'd need everyone to migrate. Not sure if this change is worth doing an incompatible bump on its own.

Most of the ecosystem including axum has already migrated to tower 0.5 so I'm not sure how it's a choice of whether to do it or not. Not doing this locks tonic users out of using any tower 0.5-based middleware and any progress done in tower-http 0.6+.

**Comment by djc** [comment]
There's already a PR for that one, too: #1556. For now, I don't think we can enable it by default for now given our MSRV, and I think the stance of the Rust Project is that RPITIT is "discouraged for general use in public traits" due to semver hazards while we don't have RTN.

**Comment by kanpov** [comment]
Anyway, if the async_trait removal is not justifiable, I still think either this needs to be shipped or if we're really committing for tonic holding back its tower version, hold back the axum version with a `<=` version bound so that incompatible axum and tonic don't get compiled together (which I think is an absolutely awful idea, but technically not breaking?).

**Comment by tottoto** [comment]
This pull request is a duplicate of an existing pull request. And since "async fn in traits" is not related to updating of tower dependency, it doesn't seem like an appropriate place to discuss it.

**Comment by kanpov** [comment]
> This pull request is a duplicate of an existing pull request. And since "async fn in traits" is not related to updating of tower dependency, it doesn't seem like an appropriate place to discuss it.

Sure, but I would like for at least the original to get merged so that tonic isn't seemingly purposefully lagging behind tower, while axum which it uses as an internal framework already has upgraded.

**Pull request closed without merging**
