### PR TITLE
Use a new prost ServiceGenerator finalizer to fix duplicate client and server definitions

### LINKED ISSUE #38: Client/Server /can be/ duplicated into their include files
### Version

master: afa9d9d236b7ca96d70d696ab38aadac7cdf41ff

### Platform

Linux RILEY-LT 4.19.43-microsoft-standard #1 SMP Mon May 20 19:35:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Crates

cargo-build

### Description

When using includes it seems like the client/server are generated into the include file output. This only seems to happen under certain conditions, I believe related to compiling multiple protos at once via `tonic_build::configure().compile(&["proto/health.proto", "proto/test.proto"], &["proto"]).unwrap();`

Repro here:

https://github.com/rlabrecque/tonic_include_repro

Specifically see: https://github.com/rlabrecque/tonic_include_repro/blob/master/src/proto/google.protobuf.rs

### PR DESCRIPTION
**Pull request by parasyte**
Note: This PR is in draft mode until the dependent PR in `prost` is accepted and released: https://github.com/danburkert/prost/pull/241

## Motivation

Fixes #38

This change allows `tonic-build` to properly group all services from multiple `.proto` files into a single package namespace.

## Solution

Defer code generation to the end of all package processing.

### CODE REVIEW

**Comment by parasyte** [comment]
Ah jeez, failures in cargo-deny and tests that I didn't touch at all... Maybe these will get sorted in master in the meantime and this PR will be fixed by merge or rebase! 😉

**Comment by parasyte** [comment]
I'm not happy with the new requirement that user code has to include all packages explicitly. Go doesn't have this problem because it will happily pull all packages into scope from a single `import` directive.

I don't see an obvious way to auto-include packages within the generated source. The conflict is that imports in protobuf are "file level" and includes in tonic-build are "package level".

**Comment by parasyte** [comment]
I see, this is actually a bug! The client and server modules are being output to the wrong package. I will be addressing this tomorrow.

**Comment by alce** [comment]
@parasyte the cargo-deny is failing in part because of a duplicated version of crossbeam-queue, which is addressed here #145 and in part because you are referencing a different version of prost-build.

We'll need #145 to be merged first, or at least the commits that fix the crossbeam duplication and then fix the prost-build issue here

**Comment by parasyte** [comment]
Ok, we're good here. All tests are passing, just waiting for `prost-build` 0.5.1 and @alce's `crossbeam-queue` patch for the cargo deny checks to pass.

**Comment by jen20** [comment]
@parasyte I'll look at resolving the issue with cargo-deny shortly, it's affected quite a few of our open PRs right now.

**Comment by LucioFranco** [comment]
This looks good! Once prost gets a publish out we can merge this! Thanks!

**Comment by parasyte** [comment]
That sounds great. I'll keep the PR as a draft until I can update `Cargo.toml` with whatever prost version gets released.

**Comment by parasyte** [comment]
Looks like #173 fixes this by namespacing the `client/server` modules separately.

**Comment by LucioFranco** [comment]
@parasyte yup, thank you for this contribution sorry we couldn't get it in, but also looks like prost is a bit slow on upgrading anyways. I am gonna close this as it seems its been solved for you!

**Comment by parasyte** [comment]
I haven't actually used the new code yet, but I am interested in trying it.

**Pull request closed without merging**
