### PR TITLE
feat(types): Add gRPC Richer Error Model support

### PR DESCRIPTION
**Pull request by flemosr**
## Motivation

The [gRPC richer error model] is quite useful to send additional feedback to clients, and is supported by many gRPC libraries in other languages.

## Solution

This PR adds richer error model support to `tonic-types`, as per [#1034]. Example servers and clients were also added.

[gRPC richer error model]: https://www.grpc.io/docs/guides/error/
[#1034]: https://github.com/hyperium/tonic/issues/1034

### CODE REVIEW

**Comment by flemosr** [comment]
Note: there are links at the bottom of the added `README.md` that are supposed to point to the crate docs. They would have to be updated to point to the correct released version of `tonic-types`.

**Comment by LucioFranco** [comment]
Thank you for this! This is quite a large PR and will likely take me a while to review. Do you think you could reduce this into multiple PRs that we can merge independently?

**Comment by flemosr** [comment]
Hi! Happy to contribute. I think the new code can be more or less evenly splitted between the functionallity corresponding to each standard error message type (`BadRequest`, `RetryInfo`, etc). I could add only the functionallity corresponding to `BadRequest` on the first PR, and add support for the other error types in subsequent PR's. Would this approach work better?

**Comment by LucioFranco** [comment]
@flemosr yeah that would be great! Thanks

**Comment by flemosr** [comment]
Hi! The first PR is still quite big, but most of it is the new proto file, docs and tests. The following ones can be smaller

**Pull request closed without merging**
