### PR TITLE
chore(docs): Update docs to mention new protoc requirements in tonic >= 0.8.0

### PR DESCRIPTION
**Pull request by o-agassizii**
This PR seeks to make the docs clear on new protoc requirements in tonic >= 0.8.0

## Motivation

This PR is for issue https://github.com/hyperium/tonic/issues/1049

## Solution

Update docs to include clear mention of new protoc requirements in tonic >= 0.8.0

### CODE REVIEW

**Comment by o-agassizii** [comment]
@LucioFranco This draft adds mention of protoc requirements to main README. In addition to that I will now look over the other docs to see if there are any places where I think this should be mentioned.

**Comment by o-agassizii** [comment]
@LucioFranco the only other place in the docs where I see it as obviously useful to mention the dependency on `protoc` is in the README of the examples subdirectory, so I added text about it there as well.

IMO this PR is ready for merging, let me know what you think.

**Review by LucioFranco — COMMENTED** [review]
Thanks!

**Review by LucioFranco — APPROVED** [review]
oops meant to approve lol

**Pull request merged**
