### PR TITLE
[tonic-web] Fix CORS trait issue when using tonic_web::enable

### PR DESCRIPTION
**Pull request by mdrach**
## Motivation

The grpc-web README example doesn't compile due to an unimplemented trait in `tower_http::cors::Cors`.  
It seems related to [this PR](https://github.com/hyperium/tonic/pull/1123), which added the tower_http Cors layer wrapper to `tonic_web::enable`. 

## The error
```bash
error[E0277]: the trait bound `tower_http::cors::Cors<GrpcWebService<GreeterServer<MyGreeter>>>: NamedService` is not satisfied
   --> examples/src/grpc-web/server.rs:44:22
    |
44  |         .add_service(tonic_web::enable(greeter))
    |          ----------- ^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `NamedService` is not implemented for `tower_http::cors::Cors<GrpcWebService<GreeterServer<MyGreeter>>>`
    |          |
    |          required by a bound introduced by this call
    |
    = help: the following other types implement trait `NamedService`:
              GreeterServer<T>
              GrpcWebService<S>
              tonic::service::interceptor::InterceptedService<S, F>
              tower::util::either::Either<S, T>
note: required by a bound in `Server::<L>::add_service`
   --> /home/ubuntu/repos/tonic/tonic/src/transport/server/mod.rs:347:15
    |
347 |             + NamedService
    |               ^^^^^^^^^^^^ required by this bound in `Server::<L>::add_service`

For more information about this error, try `rustc --explain E0277`.
```

### Reproducing the error
You can repro the issue by cloning the tonic repo and modifying the code in [this example](https://github.com/hyperium/tonic/blob/9f716d841184b8521720c6ed941af137ca2ee6a0/examples/src/grpc-web/server.rs#L30).
```diff
...
    Server::builder()
        .accept_http1(true)
-        .layer(GrpcWebLayer::new())
-        .add_service(greeter)
+        .add_service(tonic_web::enable(greeter))
        .serve(addr)
        .await?;
...
```
Then run `cargo run -p examples --bin grpc-web-server`

## Solution

Added `NamedService` impl for `tower_http::cors::Cors<S>`.  Open to feedback on where exactly this should live.

Also made the grpc-web server example consistent with the README.  It now uses the `tonic_web::enable` helper which enables CORS support by default.  As stated in [this issue](https://github.com/hyperium/tonic/issues/270), CORS support is needed for a browser client to talk to a tonic server without a proxy.  I imagine this is what the typical tonic-web user wants.

After making this change, a grpc-web client running in my browser is able to talk to my tonic-web server without issue.

### CODE REVIEW

**Comment by LucioFranco** [comment]
I think the readme is outdated so I updated it here https://github.com/hyperium/tonic/pull/1292 since this should be the new way to do it rather than the old way.

**Comment by mdrach** [comment]
> I think the readme is outdated so I updated it here #1292 since this should be the new way to do it rather than the old way.

Do we want to enable `CORS` by default in the common example, though?  This will make using tonic-web a lot easier to get started with for newcomers.

**Comment by LucioFranco** [comment]
> Do we want to enable CORS by default in the common example, though? This will make using tonic-web a lot easier to get started with for newcomers.

I believe we should be pointing people to use `tower_http::Cors`, if I remember correctly from the change PR.

**Comment by nrot** [comment]
Hello! Is there anything I can do to speed up the process?

**Comment by dragonnn** [comment]
I am trying to get this patch working on a cloned version but I am still getting error:
```
error[E0277]: the trait bound `tower_http::cors::Cors<GrpcWebService<models::proto::users::user_service_server::UserServiceServer<UserGreeter>>>: NamedService` is not satisfied
   --> server/src/grpc/mod.rs:77:22
    |
77  |         .add_service(tonic_web::enable(user_gretter))
    |          ----------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `NamedService` is not implemented for `tower_http::cors::Cors<GrpcWebService<models::proto::users::user_service_server::UserServiceServer<UserGreeter>>>`
    |          |
    |          required by a bound introduced by this call
    |
    = help: the following other types implement trait `NamedService`:
              Cors<S>
              GrpcWebService<S>
              InterceptedService<S, F>
              console_api::instrument::instrument_server::InstrumentServer<T>
              console_api::trace::trace_server::TraceServer<T>
              models::proto::defined_alarms::defined_alarms_service_server::DefinedAlarmsServiceServer<T>
              models::proto::devices::devices_service_server::DevicesServiceServer<T>
              models::proto::generic_devices::generic_devices_service_server::GenericDevicesServiceServer<T>
            and 8 others
note: required by a bound in `tonic::transport::Server::<L>::add_service`
```
I am pretty sure that is applied... I am doing something wrong? It shows that Cors<S> does have that type implemented... and GrpcWebService. When I build without this patch Cors<S> is gone. So what I am missing here?

**Comment by LucioFranco** [comment]
Check the readme https://github.com/hyperium/tonic/tree/master/tonic-web#enabling-tonic-services and the examples for how to configure it.

**Comment by dragonnn** [comment]
So we shouldn't use tonic_web::enable at all?
They why it is for? I think it should be removed in this case.

**Comment by mdrach** [comment]
> Check the readme https://github.com/hyperium/tonic/tree/master/tonic-web#enabling-tonic-services and the examples for how to configure it.

@LucioFranco mind adding an example with how configure tonic_web with CORS?  

My understanding is that [this PR](https://github.com/hyperium/tonic/pull/1123) broke CORS support by not implementing the trait on `tower_http::cors::CorsLayer`.  This PR fixes this.

Whether we use the new builder syntax or doesn't affect the underlying issue.  This also fails with the trait issue.

```
    let cors = CorsLayer::new()...;

    Server::builder()
        .accept_http1(true)
        .layer(GrpcWebLayer::new())
        .layer(cors)
        .add_service(greeter)

```

**Comment by OppositeDragon** [comment]
> ```rust
>      .accept_http1(true)
>      .accept_http1(true)
> ```

Hello, I fail to undestand why everything else seems to be there twice. Could you please explain?

**Pull request closed without merging**
