### PR TITLE
feat(build): add `cleanup-markdown` feature flag

### LINKED ISSUE #1073: Use `cleanup-markdown` `prost_build` feature
### Crates

tonic-build

### Motivation

I just saw the new feature in `prost_build` to clean up the markup of generated code using `cleanup-markdown` feature. This has been a problem for me for a long time because googleapis protobuf files are picked up in tests and fail. This would allow for easier test flows

### Proposal

Enable `cleanup-markdown` feature of prost-build

### Alternatives

Not that I know of as prost-build is a dependency of tonic-build, not direct from my project

### PR DESCRIPTION
**Pull request by nylonicious**
Closes #1073

I also documented the feature flags.

### CODE REVIEW

**Review by LucioFranco — APPROVED** [review]
Thanks!

**Comment by LucioFranco** [comment]
Looks like we just have a CI failure that needs to be resolved before we can merge

**Comment by nylonicious** [comment]
All tests run fine on my local machine, maybe you could re-run CI? I'm pretty sure even if I push empty commit CI won't run because first time contribution to this repo.

**Comment by LucioFranco** [comment]
Ah @nylonicious since this changes the output of the generated code for `tonic-types` you will need to run `cargo test --all` then commit the extra code that was updated. That is why CI is failing.

**Comment by nylonicious** [comment]
I see, my bad. It now passes `cargo test --all --all-features` locally.

**Pull request merged**
