### PR TITLE
fix(transport): Make server builder more consitient

### PR DESCRIPTION
**Pull request by jdahlq**
## Motivation

See Issue #900 

## Solution

See Issue #900

### CODE REVIEW

**Comment by jdahlq** [comment]
I guess this might cause a silent breakage for code like this:

```rust
let router = Server::builder();
router.timeout(Duration::from_secs(10));
```

`router.timeout` would no longer do anything if not chained or reassigned. We could add a `#[must_use]` annotation (and probably should add it for all these functions which return Self), which presumably would cause a compiler error for users with such code. Not sure what the best course of action is, here.

**Comment by LucioFranco** [comment]
Yeah I think adding must use makes sense here then. If you want to go ahead and add that change here as well we can merge this.

**Comment by jdahlq** [comment]
Done.

**Comment by LucioFranco** [comment]
Can you rebase against master? I fixed the ci failure https://github.com/hyperium/tonic/pull/914

**Comment by jdahlq** [comment]
Thanks, rebased.

**Review by LucioFranco — APPROVED** [review]

**Pull request merged**
