### PR TITLE
Add a `GRPC_CONTENT_TYPE` for "application/grpc".

### PR DESCRIPTION
**Pull request by ikrivosheev**
This is continue for: https://github.com/hyperium/tonic/pull/1648

### CODE REVIEW

**Comment by djc** [comment]
Has some failures in CI which will need to be addressed.

**Comment by ikrivosheev** [comment]
@djc it's strange but I cannot reproduce it local...

**Comment by djc** [comment]
> @djc it's strange but I cannot reproduce it local...

Run `cargo update`.

**Comment by ikrivosheev** [comment]
@djc thanks, fixed.

**Comment by djc** [comment]
Thanks!

**Pull request merged**
