### PR TITLE
tonic: Introduce a new method on Endpoint to override the origin

### PR DESCRIPTION
**Pull request by QuentinPerez**
## Motivation

At @znly, we use Envoy as a service mesh to distribute the traffic across the services.
Meaning that:
- we have an auto-scaled farm of Envoy which proxy the entire traffic.
- we have to refresh the IPs periodically (due to auto-scaling).
- we have to talk to the IPs directly.

That said, the requests end with an unavailable error, why? because Envoy is called with the URI (the IP in our case) and can't determine which service we are trying to reach.

## Solution

A new method named `origin` has been added to override the origin sent.
We tried it in production and it's working fine.
Let me know if you have a better solution.

### CODE REVIEW

**Comment by QuentinPerez** [comment]
@LucioFranco 👋🏻
Let me know if you need more explanation or time to review this PR

**Review by LucioFranco — CHANGES_REQUESTED** [review]
LGTM only thing missing I think is a simple unit test.

**Review by LucioFranco — APPROVED** [review]
Thanks!

**Comment by QuentinPerez** [comment]
@LucioFranco thx ! do you think that we could have a minor soon ? do not want to stay on my fork too long :)

**Pull request merged**
