### PR TITLE
chore: Bump msrv to 1.60

### PR DESCRIPTION
**Pull request by tottoto**
Tonic's msrv might be 1.60 due to axum 0.6.

### CODE REVIEW

**Comment by davidpdrsn** [comment]
Oh yes thats. I forgot that axum 0.6 increased the MSRV to 1.60.

**Comment by LucioFranco** [comment]
We need a msrv ci test as well. @tottoto would you be interested in adding that?

**Comment by tottoto** [comment]
I ported msrv test from hyper.

**Review by LucioFranco — APPROVED** [review]
Thank you!

**Pull request merged**
