### PR TITLE
Grpc-web proxy

### PR DESCRIPTION
**Pull request by zancas**
## Motivation
I'm interested in @john-hern 's tonic-based grpc-web bridge.
His PR:  #288 has minor formatting issues
I ran `cargo fmt` to fix them.   I'm opening this PR to check that the CI lint checks pass.

### CODE REVIEW

**Comment by zancas** [comment]
Reopening to continue leveraging CI.

**Comment by LucioFranco** [comment]
Hey! Thanks for opening this. I am currently on vacation and I want to think a bit about how we want to approach this. Will get back in a few weeks, sorry for the delay but this PR is quite big so want to make sure we do it right :)

**Comment by LucioFranco** [comment]
Hey! Sorry for the delay on this! I don't know much about the grpc-proxy stuff but would you be able to write up a bit on what is going no here? I want to aim for this to go into a 0.3 release but need to focus on a few important bug fixes before we get this in.

**Comment by zancas** [comment]
Hi @LucioFranco I'll try to get a summary of where we're at done by tomorrow.

**Comment by zancas** [comment]
Hi @LucioFranco we're aiming to update [tower examples](https://github.com/tower-rs/examples).

The plan is:

(0) modernize the crate such that it builds
(1 or 2) Then get the crate, or a feature gated subset,  to build against WASM.
(2 or 1) Potentially build [this PR](https://github.com/tower-rs/examples/issues/3) against WASM.

The objective is to have an example tower http-client that builds against WASM as a step towards building a gRPC client in the browser. 

That is, our approach (which I think is consistent with your suggestion) is to specify a tower Service with a from-browser (over `fetch`) transport.   We want to establish that we can build some simpler examples of tower Service implementations against WASM.

**Comment by LucioFranco** [comment]
That sounds like a plan, I would also like to suggest that we do this in a separate crate in the workspace as well so that we can iterate on it without affecting the rest of the project.

**Comment by zancas** [comment]
Do you mean move the examples crate `https://github.com/tower-rs/examples` into `https://github.com/tower-rs/tower`  ?   So it would be in the `tower` workspace adjacent to e.g. `tower-layer`, with a name like:  `tower-examples`?

**Comment by LucioFranco** [comment]
Actually, I realized over the weekend that this approach is actually probably what we want! There are plans to extract the transport into its own crate but that is further down the line. 

As for the WASM compiling etc I have not done much testing there. Let me know what you need from me to get this merged! Thanks a ton for getting this going again :smile:

**Comment by gustav3d** [comment]
How is it going ?

**Comment by LucioFranco** [comment]
Superseded by https://github.com/hyperium/tonic/pull/455

**Pull request closed without merging**
