### PR TITLE
chore(transport): Upgrade rustls and base64

### PR DESCRIPTION
**Pull request by repi**

### CODE REVIEW

**Comment by jen20** [comment]
Hi @repi! Thanks for the pull request here. The CI failure you're seeing is not actually a result of your change, we'll need to either tweak the cargo-deny settings to avoid removing our dependency on `spin` or take one of the other actions. In the interests of getting your PR merged as soon as possible, I think the first option is the best for now, I'll look at this shortly.

**Comment by repi** [comment]
I was going to PR `rustls` also about upgrading to `base64` 0.11, so we can wait with this one until `rustls` has upgraded so one doesn't bring in multiple versions of it

**Comment by LucioFranco** [comment]
@repi thanks! Yeah, once rustls gets a publish on crates io lets do both of them in here and then make deny happy. :)

**Comment by repi** [comment]
@LucioFranco new rustls 0.17 out now that uses this

**Comment by LucioFranco** [comment]
@repi perfect, I am going to coordinate this with a new 0.2 release of tonic since we expose rustls in our public API.

Looks like we need to bump rustls' version to make deny happy too :)

**Comment by LucioFranco** [comment]
@repi friendly ping :) Seems like we can finally merge this and update rustls?

**Comment by repi** [comment]
@LucioFranco there, tested upgrading rustls crates as well now!

**Pull request merged**
