### PR TITLE
fix(codec): Enforce encoders/decoders are `Sync`

### LINKED ISSUE #81: Consider making `Streaming<T>` Sync
### Crates

Main Crate

### Motivation

I'm trying to output a unidirectional tonic gRPC stream via SSE using warp. I'm using warp from https://github.com/seanmonstar/warp/pull/265 to be able to use it with async await. Changing warp to be compatible with async / await requires that all responses handed over to warp (and in turn handed over to hyper) to be `Sync`. However, the stream returned from a streaming gRPC response is not `Sync`.

### Proposal

Rustc complains that the `decoder` specifically is the part that is not sync: https://github.com/hyperium/tonic/blob/5d0a7955541509d2dbfdb9b689fb57cd2b842172/tonic/src/codec/decode.rs#L22

As far as I can see, `decoder` is not accessible from the outside, and thus it should be safe to mark the whole `Streaming` struct as `Sync`. I would be happy to file a PR for that.

### Alternatives

I don't see any, because AFAIK the `Sync` bound stems from a layer deep down inside `hyper`, and I guess it's unfeasible to change that somehow to remove it.

### PR DESCRIPTION
**Pull request by LucioFranco**
cc @NeoLegends

Closes #81

### CODE REVIEW

**Comment by LucioFranco** [comment]
Yeah...this will be a bit harder than anticipated...

**Comment by NeoLegends** [comment]
Yeah, this is the other option. I guess you're in the best position to know which bounds you will need and you will be able to satisfy in tonic.

For this implementation route we'd also want to add a test that ensures `Streaming` _stays_ sync (when adding new members).

**Comment by LucioFranco** [comment]
@seanmonstar would you be able to take a look at this?

**Comment by seanmonstar** [comment]
What I'm about to say sounds dumb: for trait objects, the order of additional auto traits matters, and most places write them as `dyn Foo + Send + Sync`. That's to say, `dyn Foo + Sync + Send` isn't the same thing. 😭

**Comment by LucioFranco** [comment]
@seanmonstar all i can say is lol

**Comment by NeoLegends** [comment]
Does this put #82 back on the table?

**Comment by LucioFranco** [comment]
@seanmonstar can I get your +1 on this before we merge?

**Pull request merged**
