### PR TITLE
chore: Update cargo-deny config

### PR DESCRIPTION
**Pull request by tottoto**
Updates it to support current project status.

### CODE REVIEW

**Comment by LucioFranco** [comment]
I believe the deny check isn't running in CI, we should probably fix that if we want to keep this up to date.

**Comment by tottoto** [comment]
Fixed it. However I noticed that tonic depends on MPL-2.0 because of webpki-roots. It is a copyleft license. Should us allow to use it in the deny config?

**Comment by LucioFranco** [comment]
Yeah, we can allow it.

**Comment by tottoto** [comment]
The copyleft licenses seem to be warned for default. I added `copyleft = "deny"` config to make the cargo-deny job fail due to MPL-2.0 in https://github.com/hyperium/tonic/pull/1169/commits/8e7a949907f7d0c3b9df049b7c31db2bee510d2f ([the failed ci](https://github.com/hyperium/tonic/actions/runs/3626168774/jobs/6114916935)), and allowed it explicitly in https://github.com/hyperium/tonic/pull/1169/commits/ea3a7141dc1d2f5b7cc5ed80cabd6a57d3044a9a.

**Comment by LucioFranco** [comment]
Thank you!

**Pull request merged**
