### PR TITLE
tonic-build: Builder: add {enum,message}_attributes

### PR DESCRIPTION
**Pull request by g0hl1n**
## Motivation

The latest prost-build introduced [enum_attribute](https://docs.rs/prost-build/0.11.6/prost_build/struct.Config.html#method.enum_attribute) and [message_attribute](https://docs.rs/prost-build/0.11.6/prost_build/struct.Config.html#method.message_attribute) configurations. We should support it.

## Solution

Update prost-build to v0.11.6 and add the enum_attribute and message_attribute forwarders.

### CODE REVIEW

**Comment by LucioFranco** [comment]
Should probably add message attribute as well? https://github.com/tokio-rs/prost/commit/14ac71ef3300d49d04392e7963d6afc2eaf6f2c4#diff-702d1c883416266db565804e8243178a5e3b59e9c22dff7d3161247d13aad208R502

**Comment by g0hl1n** [comment]
ACK. Will update the PR accordingly.

**Review by LucioFranco — APPROVED** [review]
Thanks!

**Comment by g0hl1n** [comment]
Forgot to run cargo fmt on the message_attributes patch. I've updated the PR. Sorry for missing it on the first try.

**Comment by Hallot** [comment]
Thank you [g0hl1n](https://github.com/g0hl1n).  
@LucioFranco Would it possible to have a new release soon with this feature? That would be most appreciated, thank you.

**Comment by dado0583** [comment]
+1. Would love to use this to add the derive_builder to the message generated code so that I can generate protos without explicitly providing every field (https://crates.io/crates/derive_builder)

Is there anything I can do to help get the release out @g0hl1n ?

(cc @samiam376)

**Comment by LucioFranco** [comment]
It might be a bit to get a release out I believe there are some breaking changes on master and I am traveling over the next few weeks (and was just travelling). So I will need some time to sort that out. Sorry about that.

**Pull request merged**
