### PR TITLE
chore(examples): Call Routes::prepare

### PR DESCRIPTION
**Pull request by tottoto**
Calls `Routes::prepare` in examples.

### CODE REVIEW

**Comment by djc** [comment]
Why? What does it do/why is it valuable? If it works without it, it looks like pure noise.

**Comment by tottoto** [comment]
No, it is not noise. This is recommended because it uses `axum`'s router internally. Examples should show how it should be used.

**Comment by djc** [comment]
You haven't answered my question. I mean "noise" not in a disparaging but in a technical sense, as in, code that is unnecessary (since it apparently compiles just fine without it). So why is it better to call `prepare()` on these?

**Comment by djc** [comment]
Okay, can you link that recommendation here? Essentially I'm asking why Axum recommends this.

**Comment by tottoto** [comment]
https://docs.rs/axum/0.7.5/axum/routing/struct.Router.html#a-note-about-performance

**Review by djc — APPROVED** [review]

**Pull request merged**
