### PR TITLE
butte integration

### PR DESCRIPTION
**Pull request by magnet**
This is a work-in-progress MR based on @Perlmint's work to integrate flatbuffers in tonic using butte.

There are a few things left in `butte-build` to make this happen in order to have a trait bound comparable to Prost's `Message` as an associated type for `ButteCodec` (TODO).

### CODE REVIEW

**Comment by cpcloud** [comment]
This is looking really good.

**Comment by ufosky** [comment]
It's a good feature

**Comment by LucioFranco** [comment]
@magnet do you have a status update on this?

**Comment by magnet** [comment]
> @magnet do you have a status update on this?

I've been held up on other stuff, and I have other fixes in butte incoming as well. 
Last time we discussed it was not clear to me if you wanted this in `tonic` itself or as a tonic integration crate in `butte` (notably because of semantic versioning).  Let's discuss this on Discord :)

**Comment by jon-chuang** [comment]
You know, the path to flatbuffers may not be as painful as maintaining something like butte. 

What if one just wrapped the flatc compiler's (C++) intermediate outputs in Rust types? https://github.com/google/flatbuffers/blob/master/src/idl_gen_rust.cpp

**Pull request closed without merging**
