### PR TITLE
chore: Add clippy to ci

### PR DESCRIPTION
**Pull request by tottoto**
Adds clippy check to ci.

### CODE REVIEW

**Comment by LucioFranco** [comment]
I am almost more inclined to not include clippy in ci but to accept clippy PRs as them come. Mostly this is due to my frustrations of new versions of clippy adding new lints such that it blocks PRs that add unrelated things.

**Comment by tottoto** [comment]
That makes sense. I understand your point and agree with you. So how do you think about lock the clippy version to the msrv for minimal lint (if it is feasable). Is it acceptable?

**Comment by tottoto** [comment]
I'll try to implement it.

**Comment by LucioFranco** [comment]
Yeah, I am ok to lock the clippy version so that _new_ code get caught but old code doesn't cause issues when a new version comes out.

**Review by LucioFranco — APPROVED** [review]

**Comment by LucioFranco** [comment]
on a sidenote are you on discord in the tokio server?

**Comment by tottoto** [comment]
I have to fix this warning.

```
warning: unknown lint: `clippy::derive_partial_eq_without_eq`
 --> tests/root-crate-path/src/main.rs:1:9
  |
1 | #[allow(clippy::derive_partial_eq_without_eq)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unknown_lints)]` on by default
```

**Comment by tottoto** [comment]
Ignores unknown lints and makes job fail when clippy reports warnings.

**Comment by tottoto** [comment]
Done. I think this is ready to be reviewed.

**Comment by tottoto** [comment]
> on a sidenote are you on discord in the tokio server?

I'm not on there.

**Review by LucioFranco — APPROVED** [review]

**Pull request merged**
